version: '3.8'
services:
  localstack:
    image: localstack/localstack:2.3
    environment:
      - SERVICES=sns,sqs,dynamodb
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "bash", "-c", "awslocal sns list-topics >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10
